name: sentinela
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8   
  go_router: ^15.1.2
  provider: ^6.1.5
  google_fonts: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  dio: ^5.8.0+1
  intl: ^0.20.2
  flutter_secure_storage: ^7.0.0
  flutter_dotenv: ^5.1.0
  pdf: ^3.11.3
  printing: ^5.14.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  internet_connection_checker_plus: ^2.9.0
  image_cropper: ^9.1.0
  image_picker: ^1.2.0
  url_launcher: ^6.3.2
  xml: ^6.6.1
  file_picker: ^10.3.3
  google_maps_flutter: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_regular.ttf
